[build]
  command = "next build"
  publish = "out"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/telegram"
  to = "/.netlify/functions/telegram"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200